### ISSUE TITLE
Unable to Use OpenRouter Models – `base_url` truncated and `model` URL-encoded

### ISSUE THREAD

**Issue by WongShan5678** [microsoft/windows-ai-studio#231]
I'm trying to use OpenRouter models with the extension, but requests are not being sent as expected.
Here’s my model configuration:
```yaml
name: OpenRouter-anthropic/claude-sonnet-4
chat_completion_url: https://openrouter.ai/api/v1
headers:
  Authorization: 'Bearer <TOKEN>'
api_model_name: 'anthropic/claude-sonnet-4'
```
I always get `This model doesn't return token count.` in the playground

When I click **View Code**, I see this:
```python
client = OpenAI(
    base_url = "https://openrouter.ai",
    api_key = os.environ["CUSTOM_OPENAI_API_KEY"],
)

response = client.chat.completions.create(
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "INSERT_INPUT_HERE",
                },
            ],
        },
    ],
    model = "anthropic&#x2F;claude-sonnet-4",
    max_tokens = 4096,
)
```
Problems:
- `base_url` is set to `https://openrouter.ai instead of the expected https://openrouter.ai/api/v1.`
- The `model` name is encoded (`anthropic&#x2F;claude-sonnet-4`) rather than plain text (`anthropic/claude-sonnet-4`).
